# Generated by Django 4.0.4 on 2022-05-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=10, unique=True, verbose_name='Номер группы')),
                ('group_title', models.CharField(choices=[('МОАИС', 'Мат. обеспечение и администрирование информационных систем'), ('ПИ', 'Прикладная информатика'), ('ПМ', 'Прикладная математика и инофрматика'), ('Пед. обр', 'Педагогическое образование с двумя профилями подготовки'), ('Не студенческая группа', 'Не студенческая группа')], max_length=250, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('student_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('account_id', models.IntegerField(unique=True, verbose_name='id аккаунта')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
