# Generated by Django 4.0.4 on 2022-05-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=10, verbose_name='Номер группы')),
                ('group_title', models.CharField(max_length=250, verbose_name='Имя группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('student_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('group_number', models.CharField(max_length=10, verbose_name='Номер группы')),
                ('account_id', models.IntegerField(verbose_name='id аккаунта')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
