# Generated by Django 4.0.4 on 2022-05-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAcmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('BE', 'Для начинающих'), ('ME', 'Средний'), ('HA', 'Сложный')], default='BE', max_length=2)),
                ('task_list', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_solved_acmp_base',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
