# Generated by Django 4.0.4 on 2022-05-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_taskacmp_student_student_solved_acmp_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskacmp',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Для начинающих'), ('MEDIUM', 'Средний'), ('HARD', 'Сложный')], default='BEGINNER', max_length=15),
        ),
    ]
